package com.NewsCred.backend.service;

import org.springframework.stereotype.Service;

import java.net.HttpURLConnection;
import java.net.URL;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class ImageVerificationService {

    private static final List<String> STOCK_PHOTO_SITES = Arrays.asList(
        "shutterstock", "istock", "gettyimages", "adobestock", "freepik",
        "depositphotos", "123rf", "pixabay", "pexels", "unsplash",
        "canva", "storyblocks", "envato", "dreamstime", "alamy"
    );

    private static final List<String> AI_IMAGE_INDICATORS = Arrays.asList(
        "ai generated", "generated by ai", "midjourney", "dall-e", "stable diffusion",
        "artificial intelligence", "ai image", "synthetic", "created by ai",
        "generated with ai", "ai art", "generative ai"
    );

    private static final List<String> IMAGE_DOMAINS = Arrays.asList(
        "i.imgur.com", "images.unsplash.com", "images.pexels.com",
        "cdn.pixabay.com", "static.wixstatic.com", "s3.amazonaws.com"
    );

    private static final int MAX_IMAGES_TO_ANALYZE = 15;

    public ImageVerificationResult verifyImagesFromUrls(List<String> imageUrls) {
        ImageVerificationResult result = new ImageVerificationResult();
        
        if (imageUrls == null || imageUrls.isEmpty()) {
            result.setImageCount(0);
            result.setStatus("NO_IMAGES");
            result.setMessage("No images found in this article.");
            result.setScore(0.5);
            result.setRecommendation("Neutral - no images to verify.");
            return result;
        }
        
        List<String> processedUrls = imageUrls.stream()
            .limit(MAX_IMAGES_TO_ANALYZE)
            .collect(java.util.stream.Collectors.toList());
        
        result.setImageCount(processedUrls.size());
        
        int stockPhotoCount = 0;
        int aiIndicatorCount = 0;
        int manipulationCount = 0;
        int reachableCount = 0;
        
        for (String url : processedUrls) {
            if (isStockPhoto(url)) {
                stockPhotoCount++;
            }
            if (hasAIIndicatorsInUrl(url)) {
                aiIndicatorCount++;
            }
            if (hasManipulationInUrl(url)) {
                manipulationCount++;
            }
            if (isImageReachable(url)) {
                reachableCount++;
            }
        }
        
        result.setStockPhotoCount(stockPhotoCount);
        result.setHasAIIndicators(aiIndicatorCount > 0);
        result.setHasManipulationSigns(manipulationCount > 0);
        result.setAIIndicatorCount(aiIndicatorCount);
        result.setManipulationCount(manipulationCount);
        result.setReachableCount(reachableCount);
        
        double score = calculateImageScore(result);
        result.setScore(score);
        
        String status = determineStatus(result);
        result.setStatus(status);
        result.setMessage(generateMessage(result));
        result.setRecommendation(generateRecommendation(result));
        
        return result;
    }

    public ImageVerificationResult verifyImages(String content) {
        ImageVerificationResult result = new ImageVerificationResult();
        
        List<String> imageUrls = extractImageUrls(content);
        if (imageUrls.isEmpty()) {
            result.setImageCount(0);
            result.setStatus("NO_IMAGES");
            result.setMessage("No images found in this article.");
            result.setScore(0.5);
            result.setRecommendation("Neutral - no images to verify.");
            return result;
        }
        
        return verifyImagesFromUrls(imageUrls);
    }

    private List<String> extractImageUrls(String content) {
        List<String> urls = new ArrayList<>();
        if (content == null) return urls;
        
        Pattern pattern = Pattern.compile(
            "https?://[^\\s\"]+\\.(jpg|jpeg|png|gif|webp|bmp|svg)",
            Pattern.CASE_INSENSITIVE
        );
        Matcher matcher = pattern.matcher(content);
        
        while (matcher.find()) {
            urls.add(matcher.group());
        }
        
        pattern = Pattern.compile("src=[\"']([^\"']+)[\"']", Pattern.CASE_INSENSITIVE);
        matcher = pattern.matcher(content);
        
        while (matcher.find()) {
            String src = matcher.group(1);
            if (src.matches(".*\\.(jpg|jpeg|png|gif|webp|bmp|svg).*")) {
                urls.add(src);
            }
        }
        
        Set<String> uniqueUrls = new LinkedHashSet<>(urls);
        return new ArrayList<>(uniqueUrls);
    }

    private boolean isStockPhoto(String url) {
        String lowerUrl = url.toLowerCase();
        for (String site : STOCK_PHOTO_SITES) {
            if (lowerUrl.contains(site)) {
                return true;
            }
        }
        for (String domain : IMAGE_DOMAINS) {
            if (lowerUrl.contains(domain)) {
                return true;
            }
        }
        return false;
    }

    private boolean hasAIIndicatorsInUrl(String url) {
        String lowerUrl = url.toLowerCase();
        for (String indicator : AI_IMAGE_INDICATORS) {
            String searchPattern = indicator.replace(" ", "");
            if (lowerUrl.contains(searchPattern) || 
                lowerUrl.contains(indicator.replace(" ", "-"))) {
                return true;
            }
        }
        return lowerUrl.contains("midjourney") || 
               lowerUrl.contains("dalle") || 
               lowerUrl.contains("stable-diffusion") ||
               lowerUrl.contains("openai") ||
               lowerUrl.contains("generated") ||
               lowerUrl.contains("synthetic");
    }

    private boolean hasManipulationInUrl(String url) {
        String lowerUrl = url.toLowerCase();
        String[] manipulationPatterns = {
            "manipulated", "doctored", "fake", "photoshopped",
            "edited", "altered", "modified", "processed",
            "filtered", "enhanced", "retouched", "adjusted"
        };
        for (String pattern : manipulationPatterns) {
            if (lowerUrl.contains(pattern)) {
                return true;
            }
        }
        return false;
    }

    private boolean isImageReachable(String urlString) {
        try {
            URL url = new URL(urlString);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("HEAD");
            connection.setConnectTimeout(3000);
            connection.setReadTimeout(3000);
            int responseCode = connection.getResponseCode();
            connection.disconnect();
            return responseCode >= 200 && responseCode < 400;
        } catch (Exception e) {
            return false;
        }
    }

    private double calculateImageScore(ImageVerificationResult result) {
        double score = 0.5;
        
        int imageCount = result.getImageCount();
        if (imageCount > 0) {
            score += 0.1;
        }
        if (imageCount >= 3) {
            score += 0.05;
        }
        
        if (result.getReachableCount() > 0) {
            double reachableRatio = (double) result.getReachableCount() / imageCount;
            score += reachableRatio * 0.1;
        }
        
        if (result.getStockPhotoCount() > 0) {
            double stockPenalty = 0.1 * Math.min(result.getStockPhotoCount(), 3);
            score -= stockPenalty;
        }
        
        if (result.isHasAIIndicators()) {
            score -= 0.2;
        }
        
        if (result.isHasManipulationSigns()) {
            score -= 0.3;
        }
        
        if (result.getStockPhotoCount() > 0 && result.isHasAIIndicators()) {
            score -= 0.1;
        }
        
        return Math.min(Math.max(score, 0.0), 1.0);
    }

    private String determineStatus(ImageVerificationResult result) {
        if (result.getImageCount() == 0) {
            return "NO_IMAGES";
        }
        
        if (result.isHasManipulationSigns() || result.getManipulationCount() > 2) {
            return "MANIPULATED";
        }
        
        if (result.isHasAIIndicators() || result.getAIIndicatorCount() > 1) {
            return "AI_GENERATED";
        }
        
        if (result.getStockPhotoCount() > result.getImageCount() / 2) {
            return "STOCK_PHOTOS";
        }
        
        if (result.getScore() >= 0.7) {
            return "VERIFIED";
        }
        
        return "NEEDS_REVIEW";
    }

    private String generateMessage(ImageVerificationResult result) {
        if (result.getImageCount() == 0) {
            return "This article contains no images.";
        }
        
        StringBuilder message = new StringBuilder();
        message.append("Found ").append(result.getImageCount()).append(" image(s). ");
        
        if (result.getReachableCount() < result.getImageCount()) {
            int unreachable = result.getImageCount() - result.getReachableCount();
            message.append(unreachable).append(" image(s) could not be loaded. ");
        }
        
        if (result.isHasManipulationSigns()) {
            message.append("Signs of image manipulation detected. ");
        }
        
        if (result.isHasAIIndicators()) {
            message.append("Some images may be AI-generated. ");
        }
        
        if (result.getStockPhotoCount() > 0) {
            message.append(result.getStockPhotoCount()).append(" image(s) appear to be stock photos. ");
        }
        
        if (result.getAIIndicatorCount() > 0) {
            message.append(result.getAIIndicatorCount()).append(" image(s) show AI generation indicators. ");
        }
        
        if (result.getManipulationCount() > 0) {
            message.append(result.getManipulationCount()).append(" image(s) show manipulation signs. ");
        }
        
        return message.toString();
    }

    private String generateRecommendation(ImageVerificationResult result) {
        if (result.getImageCount() == 0) {
            return "The article has no images to verify.";
        }
        
        if (result.getScore() >= 0.7) {
            return "Images appear authentic and relevant.";
        } else if (result.getScore() >= 0.4) {
            return "Images may not be authentic. Consider verifying with reverse image search.";
        } else {
            return "Images show signs of manipulation or AI generation. Exercise caution.";
        }
    }

    public static class ImageVerificationResult {
        private int imageCount;
        private int stockPhotoCount;
        private boolean hasAIIndicators;
        private boolean hasManipulationSigns;
        private int aiIndicatorCount;
        private int manipulationCount;
        private int reachableCount;
        private double score;
        private String status;
        private String message;
        private String recommendation;

        public int getImageCount() { return imageCount; }
        public void setImageCount(int imageCount) { this.imageCount = imageCount; }
        public int getStockPhotoCount() { return stockPhotoCount; }
        public void setStockPhotoCount(int stockPhotoCount) { this.stockPhotoCount = stockPhotoCount; }
        public boolean isHasAIIndicators() { return hasAIIndicators; }
        public void setHasAIIndicators(boolean hasAIIndicators) { this.hasAIIndicators = hasAIIndicators; }
        public boolean isHasManipulationSigns() { return hasManipulationSigns; }
        public void setHasManipulationSigns(boolean hasManipulationSigns) { this.hasManipulationSigns = hasManipulationSigns; }
        public int getAIIndicatorCount() { return aiIndicatorCount; }
        public void setAIIndicatorCount(int aiIndicatorCount) { this.aiIndicatorCount = aiIndicatorCount; }
        public int getManipulationCount() { return manipulationCount; }
        public void setManipulationCount(int manipulationCount) { this.manipulationCount = manipulationCount; }
        public int getReachableCount() { return reachableCount; }
        public void setReachableCount(int reachableCount) { this.reachableCount = reachableCount; }
        public double getScore() { return score; }
        public void setScore(double score) { this.score = score; }
        public String getStatus() { return status; }
        public void setStatus(String status) { this.status = status; }
        public String getMessage() { return message; }
        public void setMessage(String message) { this.message = message; }
        public String getRecommendation() { return recommendation; }
        public void setRecommendation(String recommendation) { this.recommendation = recommendation; }

        public String getStatusLabel() {
            switch (status) {
                case "VERIFIED": return "Verified";
                case "NO_IMAGES": return "No Images";
                case "STOCK_PHOTOS": return "Stock Photos";
                case "AI_GENERATED": return "AI Generated";
                case "MANIPULATED": return "Manipulated";
                case "NEEDS_REVIEW": return "Needs Review";
                default: return "Unknown";
            }
        }
    }
}